### ISSUE TITLE
[Ubuntu] Can't send image 

### ISSUE THREAD

**Issue by aerodiduch** [Ankit404butfound/PyWhatKit#116] opened 2021-08-25 02:36 UTC
Hello! Code works fine on Windows. Migrated the script to Ubuntu 18.04.3 LTS and doesn't work. At first, the code below sent the text + the address of the image as a message. (e.g. "Hello!/aa/aaa/aa") Then, I noticied that xclip was missing and installed it via sudo apt-get install xclip and now the code just sends the caption, but no image.

Tried the same code on windows and works perfectly.

The image is in the same path as the script. 

`pywhatkit.sendwhats_image(f"+549"+numero,img_path='/home/dide/Documentos/PythonX/ZorroBot/zorrito.jpg',caption="Hello",wait_time=10,tab_close=True)`

Also tried:

`pywhatkit.sendwhats_image(f"+549"+numero,img_path='zorrito.jpg',caption="Hello",wait_time=10,tab_close=True)`

Also, tried without the "img_path" and just the 'zorrito.jpg'.

But same result.

Thank you very much!

**Comment by aaryanrr** [comment] 2021-08-25 06:25
Hey @aerodiduch , can you please confirm that you are using version `0.13` of xclip as earlier versions of xclip were having issues with copying bytes from large image files.

**Comment by aerodiduch** [comment] 2021-08-29 00:39
Hi! Im so sorry for the big delay. While updating Ubuntu, the pc crashed and had to start from scratch. I now have Ubuntu 20.04.
Just installed `xsel` on 1.2 and `xclip` 0.13. I downloaded brave as my default browser. On Ubuntu 18.04 I was using Firefox. Now, I'm able to copy and paste images to WhatsApp chats with no trouble. But when I run the script, it fails. It goes and sends the caption with no image. This is the error that outputs to the console.


`[16707:16707:0828/213442.198712:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[16672:16672:0828/213442.799517:ERROR:CONSOLE(1)] "[Shields]: Can't request shields panel data. Error: No tab url specified", source: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/out/brave_extension_background.bundle.js (1)
Failed to parse JSON adblock resources: EOF while parsing a value at line 1 column 0`

Wrapping up:

Now with Ubuntu 20.04 i can manually copy-paste images into whatsapp chats. But script returns that error. Thank you and sorry for the delay

**Comment by aaryanrr** [comment] 2021-08-29 07:08
This seems to be a problem with the Brave Browser. I would recommend using Firefox/Microsoft Edge/Chrome as the script is tested and works on these browsers without any issues.

**Comment by aerodiduch** [comment] 2021-08-29 22:47
Hi! Just switched to Firefox as default browser. Everything remain the same! Not it doesnt output any error, but images are not being sent

**Comment by aaryanrr** [comment] 2021-08-30 16:10
Hi, thanks for bearing with us. Do you have `python3-tk` and `python3-dev` installed as `pyautogui` requires these two modules to function. If not, use this command to install them `sudo apt-get install python3-tk python3-dev`.

**Comment by aerodiduch** [comment] 2021-08-30 16:23
No worries! I did not had those packages installed. Now I do, but same output.  Nothing changed :(

**Comment by aaryanrr** [comment] 2021-08-30 17:43
We have tried this on our end and its a confirmed bug. We will be releasing an update soon to address this issue. Thanks for pointing it out.

**Comment by aerodiduch** [comment] 2021-08-30 18:12
Thank you for your time :)

**Comment by Delta456** [comment] 2021-09-14 16:46
I also face the same issue.

**Comment by aaryanrr** [comment] 2021-09-15 05:32
Hey @Delta456 , sorry for the inconvenience caused. We are working on a fix for this bug and it will be released with the next update.

**Comment by Delta456** [comment] 2021-09-15 06:09
Please take your time! I appreciate the work on this library as it is handy plus docs are easy to grasp as well so I am using this in my school project.

**Comment by aaryanrr** [comment] 2021-09-22 13:05
Hey all, this bug has been fixed in the new version (5.2) which will be released tomorrow. Be sure to check the updated documentation tomorrow. Thanks for reporting this!

**Closed by aaryanrr** 2021-09-22 13:05 UTC
Labels: bug

**Comment by Delta456** [comment] 2021-09-22 13:28
Please ping me when it is released. Thanks

**Comment by aaryanrr** [comment] 2021-09-22 14:09
Sure!
