### ISSUE TITLE
Message is being typed but not sent

### ISSUE THREAD

**Issue by shadowfax-ng** [Ankit404butfound/PyWhatKit#149] opened 2021-11-20 20:17 UTC
## Description

Text just stays in the whatsapp web box and doesn't get sent. Screenshot atttached.
![image](https://user-images.githubusercontent.com/66220509/142739704-8fbb2ea5-58bb-443c-b4e3-67705726ed57.png)

## To Reproduce

Run the  w.sendwhatmsg_instantly("Phonenumber",message)

## Screenshots

Please find attached

## Version Information

- OS: Windows 10
- Browser: Microsoft Edge, Google Chrome
- Python: 3.10.0
- PyWhatKit: 5.2

You can Check the PyWhatKit Version using

```py
print(pywhatkit.__VERSION__)
```

**Comment by aaryanrr** [comment] 2021-11-20 21:09
Hey @shadowfax-ng, thanks for reporting the bug. Here are a few things you can follow:
1. Do not use your mouse or keyboard while the script is running.
2. Open the folder where `pywhatkit` is installed. If you have installed it in a virtual environment it will be `venv\Lib\site-packages\pywhatkit\core`. Open the `core.py` file and edit lines 63 and 65. Increase the time of 7s to 9 or more. 

![Screenshot from 2021-11-21 02-35-22](https://user-images.githubusercontent.com/73213670/142740866-fbe829fc-450e-47f8-8039-f3f77c5ef43b.png)
.

**Comment by zheksy** [comment] 2021-11-27 11:00
i am encountering the same issue. this happens when a "starting conversation" popup appears when the whatsapp web tab is being open, and the cursor doesn't get placed at the end of the message so it can't be sent. i don't know what causes the popup since it seemingly appears at random openings, very inconsistent.

**Comment by singh88** [comment] 2021-11-28 19:41
Can confirm this is happening

**Comment by aaryanrr** [comment] 2021-11-28 20:59
Hey @zheksy and @singh88, thanks for reporting it. This is happening because when starting a new conversation with someone the mouse click on the centre happens to be on this message which then shows the popup.
![Screenshot from 2021-11-29 02-25-22](https://user-images.githubusercontent.com/73213670/143785685-90d8b441-e658-4bff-82dc-7af88dbd6aff.png)
For now you can send two or more messages in a new conversation before using the library. We'll try our best to find a solution for it.

**Comment by TomPrint** [comment] 2021-12-05 23:44
In my code, the script sendwhatmsg opens a new whatsupp window and then it hits and opens a picture (if there is a picture in conversation window with a receiver).
If you do not close the picture manually, then the message does not get sent to the receiver. (I am using Microsoft Edge).

**Comment by aaryanrr** [comment] 2021-12-08 06:33
> In my code, the script sendwhatmsg opens a new whatsupp window and then it hits and opens a picture (if there is a picture in conversation window with a receiver). If you do not close the picture manually, then the message does not get sent to the receiver. (I am using Microsoft Edge).
This is due to the cursor click that happens during the execution of the function. We are looking for an alternative way to do this.

**Comment by AdrianoDiRosa** [comment] 2021-12-23 08:25
I've solved updating sendwhatmsg_instantly
` time.sleep(15)
    pg.click(core.WIDTH / 2, core.HEIGHT / 2)
    time.sleep(wait_time - 15)`
    
changing it in

` pg.click(core.WIDTH / 2, core.HEIGHT / 2)
    time.sleep(wait_time)`
    
    I've removed row 29 and assuming time.sleep= wait time declared.
    
 Actually I'm adding a function to close tabs after messages has been sent.

**Comment by priyanhsu10** [comment] 2021-12-25 17:08
I  am facing same issue but am on. mac system

**Comment by AdrianoDiRosa** [comment] 2021-12-26 09:14
I'm using autogui to click on send button  based on mouse coordinates.
Obviously it isn't a standard way beacuse coordinates are related to screen resolution, but it's a good way for me to have script working and maybe useful to you to find a good way..

**Comment by napema** [comment] 2021-12-26 11:22
> ## Description
> Text just stays in the whatsapp web box and doesn't get sent. Screenshot atttached. ![image](https://user-images.githubusercontent.com/66220509/142739704-8fbb2ea5-58bb-443c-b4e3-67705726ed57.png)
> 
> ## To Reproduce
> Run the w.sendwhatmsg_instantly("Phonenumber",message)
> 
> ## Screenshots
> Please find attached
> 
> ## Version Information
> * OS: Windows 10
> * Browser: Microsoft Edge, Google Chrome
> * Python: 3.10.0
> * PyWhatKit: 5.2
> 
> You can Check the PyWhatKit Version using
> 
> ```python
> print(pywhatkit.__VERSION__)
> ```

import pywhatkit
import pyautogui
import time

pywhatkit.sendwhatmsg_instantly('Phone Num', 'test')
time.sleep(20)
pyautogui.click(x=1044, y=688) _[DEPENS ON YOUR SCREEN RES, USE ShareX AND ITS COLOR GRABBER TOOL TO GET COORDS]_
pyautogui.press("enter")

**Comment by napema** [comment] 2021-12-26 11:25
Hey, I got into the same issue and resolved this way:

```
import pywhatkit
import pyautogui
import time

pywhatkit.sendwhatmsg_instantly('Phone Num', 'test')

time.sleep(20)
pyautogui.click(x=1044, y=688) ##Depens on your screen resolution. Use ShareX and its Color Grabber tool to get your coords.
pyautogui.press("enter")
```

**Comment by Onyinye91-ctrl** [comment] 2021-12-26 19:13
> Hey @shadowfax-ng, thanks for reporting the bug. Here are a few things you can follow:
> 
> 1. Do not use your mouse or keyboard while the script is running.
> 2. Open the folder where `pywhatkit` is installed. If you have installed it in a virtual environment it will be `venv\Lib\site-packages\pywhatkit\core`. Open the `core.py` file and edit lines 63 and 65. Increase the time of 7s to 9 or more.
> 
> ![Screenshot from 2021-11-21 02-35-22](https://user-images.githubusercontent.com/73213670/142740866-fbe829fc-450e-47f8-8039-f3f77c5ef43b.png) .

This solution did not solve the issue. For the message to send i need to click the whatsapp sent message icon

**Comment by tadam98** [comment] 2021-12-27 09:10
Using verion print(pywhatkit.__VERSION__) Version 5.2 (Stable).
Message is only typed in the window but **not sent**.

**Comment by Onyinye91-ctrl** [comment] 2021-12-27 10:50
I am using the stable version

> Using verion print(pywhatkit.**VERSION**) Version 5.2 (Stable). Message is only typed in the window but **not sent**.

I am using the stable version 5.2

**Comment by luk2009** [comment] 2021-12-30 03:31
`def whatmsg(telef, notaw):
   hoy = datetime.datetime.now()
   hora_actual = datetime.datetime(hoy.year, hoy.month, hoy.day, hoy.hour, hoy.minute)
   hora_deseada = datetime.timedelta(minutes=2)
   salida = hora_actual + hora_deseada
   print(salida)
   kit.sendwhatmsg(telef, notaw, salida.hour, salida.minute, 35, True, 5)`


It just opens the browser and creates the message, but after the established wait time, it closes the tab and does not send the message.

Increasing wait time value works but it fails on some occasions.

**Comment by aaryanrr** [comment] 2021-12-30 08:27
> ```
>  def whatmsg(telef, notaw):
>       hoy = datetime.datetime.now()
>       hora_actual = datetime.datetime(hoy.year, hoy.month, hoy.day, hoy.hour, hoy.minute)
>       hora_deseada = datetime.timedelta(minutes=2)
>       salida = hora_actual + hora_deseada
>       print(salida)
>       kit.sendwhatmsg(telef, notaw, salida.hour, salida.minute, 35, True, 5)
> ```
> 
> It just opens the browser and creates the message, but after the established wait time, it closes the tab and does not send the message.
> 
> Increasing wait time value works but it fails on some occasions.

This is happening because WhatsApp Web in some cases takes a few more seconds to load which then interferes with the working of the script.

**Comment by aaryanrr** [comment] 2021-12-30 08:27
> > Hey @shadowfax-ng, thanks for reporting the bug. Here are a few things you can follow:
> > 
> > 1. Do not use your mouse or keyboard while the script is running.
> > 2. Open the folder where `pywhatkit` is installed. If you have installed it in a virtual environment it will be `venv\Lib\site-packages\pywhatkit\core`. Open the `core.py` file and edit lines 63 and 65. Increase the time of 7s to 9 or more.
> > 
> > ![Screenshot from 2021-11-21 02-35-22](https://user-images.githubusercontent.com/73213670/142740866-fbe829fc-450e-47f8-8039-f3f77c5ef43b.png) .
> 
> This solution did not solve the issue. For the message to send i need to click the whatsapp sent message icon

We are trying to find a permanent solution to this problem. Thanks for bearing with us!

**Comment by rvaquerizor** [comment] 2022-01-01 09:28
I am finding exactly the same issue.
I am using the _sendwhatmsg_instantly_ method to send a txt message immediately as follows:

`pywhatkit.sendwhatmsg_instantly(phone_number, message)`

I can see a new tab is opened on my browser, the destination chat is opened, and the message is written to it, but it is not sent.

```
>>> print(pywhatkit.__VERSION__)
Version 5.2 (Stable)
```

**Comment by vahidpourmohamad** [comment] 2022-01-01 13:12
same issue I was encountered

**Comment by shivakumarPabbathi** [comment] 2022-01-02 03:22
Same issue

**Comment by prpSa** [comment] 2022-01-02 10:41
First, import the keyboard library (use pip install keyboard) and then do the following changes in the last line. Also, do these changes in all press commands in core.py 

def send_message(message: str, receiver: str, wait_time: int) -> None:

    _web(receiver=receiver, message=message)
    time.sleep(7)
    click(WIDTH / 2, HEIGHT / 2)
    time.sleep(wait_time - 7)
    if not check_number(number=receiver):
        for char in message:
            if char == "\n":
                hotkey("shift", "enter")
            else:
                typewrite(char)
    keyboard.press('enter')`

**This will solve 'Message is being typed but not sent' this error**

**Comment by luk2009** [comment] 2022-01-04 04:11
I made the changes in core.py and the problem still remains.
sometimes the program sends the message and other times it doesn't

**Comment by ashwinmahantha** [comment] 2022-01-04 06:21
I am facing the same issue on Arch linux with i3wm.
Increasing timeout and using keyboard module did not help.

**Comment by rkalyankumar** [comment] 2022-01-04 06:55
I managed to make it work in my system (Ubuntu 20.04):
    https://github.com/rkalyankumar/send-whatsapp-automated-gm-message
If you are on Windows or Mac, you may not require to setup xhost and xauth settings as described in the README.md file in above github link.

**Comment by abhis021** [comment] 2022-01-06 15:45
* It worked for the very first time and after that its just opening the window and is not sending the messages .
* It doesn't work with the send message and close tab method.
* It doesn't work when there is time like this 21 09, Hence, If I give it this kind of time, it will show as error and won't execute, furthermore, if I give it as 21, 9  then that will execute it the next day.
![image](https://user-images.githubusercontent.com/43817822/148409147-4eaff405-68bc-4e0e-a222-f2290954caa1.png)

**Comment by abhis021** [comment] 2022-01-06 15:49
> Hey @shadowfax-ng, thanks for reporting the bug. Here are a few things you can follow:
> 
> 1. Do not use your mouse or keyboard while the script is running.
> 2. Open the folder where `pywhatkit` is installed. If you have installed it in a virtual environment it will be `venv\Lib\site-packages\pywhatkit\core`. Open the `core.py` file and edit lines 63 and 65. Increase the time of 7s to 9 or more.
> 
> ![Screenshot from 2021-11-21 02-35-22](https://user-images.githubusercontent.com/73213670/142740866-fbe829fc-450e-47f8-8039-f3f77c5ef43b.png) .

Tried this, but this doesn't work, still the same issue is there.

**Comment by dsantiago** [comment] 2022-01-07 13:35
Same for me, messages stays there in the box and are never dispatched...

**Comment by saukumar95** [comment] 2022-01-07 14:12
> > > Hey @shadowfax-ng, thanks for reporting the bug. Here are a few things you can follow:
> > > 
> > > 1. Do not use your mouse or keyboard while the script is running.
> > > 2. Open the folder where `pywhatkit` is installed. If you have installed it in a virtual environment it will be `venv\Lib\site-packages\pywhatkit\core`. Open the `core.py` file and edit lines 63 and 65. Increase the time of 7s to 9 or more.
> > > 
> > > ![Screenshot from 2021-11-21 02-35-22](https://user-images.githubusercontent.com/73213670/142740866-fbe829fc-450e-47f8-8039-f3f77c5ef43b.png) .
> > 
> > 
> > This solution did not solve the issue. For the message to send i need to click the whatsapp sent message icon
> 
> We are trying to find a permanent solution to this problem. Thanks for bearing with us!

Why we used coordinates to click enter button to send the message?. Instead .can we try finding something tag tags or attributes using some xpath or similar in entire screen and then try to click on. Just a thought, Not sure will that work or not.

**Comment by srimanivinay97** [comment] 2022-01-09 09:29
### IT IS WORKING

I have encountered same issue, later  I changed the 64 line in core.py  

![Screenshot 2022-01-09 at 2 31 27 PM](https://user-images.githubusercontent.com/42007271/148676352-19d0dadf-67a1-4b60-a175-326275582b1f.png)
It worked for me.

### later I changed 64 line to previous 

![Screenshot 2022-01-09 at 2 33 28 PM](https://user-images.githubusercontent.com/42007271/148676468-1b9ffda3-1759-4e85-9c6f-2f7cf2133d87.png)
again it worked .

### **It is absolutely fine if use code in first image** 

### **This is not the first time I have encountered this bug It happened in Django also** 

### **my configuration:**
macOS latest version (intel)
PyWhatKit v5.3
chrome latest version

**Comment by theCJMan** [comment] 2022-01-18 08:52
This issue is Based on #20
However #20 was closed yet I see several people still have an issue and This is still an issue for me.

### My Environment
Chrome Version 97.0.4692.71 (Official Build) (64-bit)
Win 10 V 21H1
2 monitors (Laptop screen plus 1 HDMI)
Line speed 20m/s

PyWhatKit 5.3
Python 3.9

### The Code
I had to include flask else the code would not work, 

```
import pywhatkit as wu
import flask

wu.sendwhatmsg_instantly("+27790995412", "Test this now", 15)
```

### What I found:
When code (PyCharm) is on main screen and browser on the other:
0. PyCharm has focus (naturally) 
1. New tab opens and load WhatsApp (Chrome has focus now)
2. Message is typed in text area **BUT not sent**
3. Seems <ALT> + <Tab> is pressed (sent) and then an enter is sent (This leaves an additional new line in the code)
4. Code ends

When code (PyCharm) AND browser on the other screen :
0. PyCharm has focus (naturally) 
1. New tab opens and load WhatsApp (Chrome has focus now)
2. Message is typed in text area **BUT not sent**
3. Seems <ALT> + <Tab> is pressed (sent) and then an enter is sent 
3.1. NOTE the "3rd" window or app was my FileExplorer and a word doc was highlighted
3.2. The result of the alt tab is that the File explorer receives focus and when the enter is pressed then the highlighted file (word doc) is opened...
4. Code ends

When code (PyCharm) AND browser on the MAIN screen :
0. PyCharm has focus (naturally) 
1. New tab opens and load WhatsApp (Chrome has focus now)
2. Message is typed in text area **BUT not sent**
3. **NOTE** now it seems NOT to do an <ALT> + <Tab> 
3.1. It seems the focus is still in the browser and in the WhatsApp tab...
4. Code ends

### My Fix
I am keeping the Code and Chrome on the main screen.
and had to add a few lines of code to "send" the message
```
import pywhatkit as wu
import flask
import pyautogui as pg

wu.sendwhatmsg_instantly("+27790995412", "Test this now", 15)
for i in range(10):
    pg.press("tab")
pg.press("enter")
```

**Comment by lprone** [comment] 2022-01-19 20:29
My simple fix (screen size dependent):
![image](https://user-images.githubusercontent.com/3941841/150208372-a9910c38-f62d-44be-bdb9-cc7ef320de3e.png)
Maybe click coordinates could be parameters of the function

**Comment by TomerVagenfeld** [comment] 2022-01-26 08:30
I suggest using Selenium.WebDriver instead of relaying on the UI to open up. 
That way you use Headless browser and automate messages without having the web page to visibly open.

**Comment by aaryanrr** [comment] 2022-01-30 08:07
Hey everyone, sorry for the issues you are facing. We are working to find a dynamic way of calculating the point to be clicked based on the screen size.

**Comment by lloydmcl** [comment] 2022-02-06 05:00
Is there a workaround for this issue while we await a resolution? Perhaps using an older version?

**Comment by Naman23-coder** [comment] 2022-02-06 05:09
@lloydmcl i have actually found a solution, as soon it is tested on different computers it will be released

**Comment by lloydmcl** [comment] 2022-02-06 05:10
@Naman23-coder you're a hero. Please let me know if I can help in any way :)

**Comment by Naman23-coder** [comment] 2022-02-06 08:13
@lloydmcl i opened draft pull request at https://github.com/Ankit404butfound/PyWhatKit/pulls/184

**Comment by masmedh** [comment] 2022-02-22 12:28
> 

hi @priyanhsu10  - is the problem that you reported resolved? - i am also using the mac system and tried all the options as well.

**Comment by MahdiPlayer1080** [comment] 2022-02-28 10:46
It is difficult for me to send messages in the group. The problem is that it opens Chrome and WhatsApp, but does not even type the message.

**Comment by Naman23-coder** [comment] 2022-02-28 11:21
@MahdiPlayer1080 try setting wait time to 20

**Closed** 2022-03-06 15:52 UTC
Labels: bug

**Comment by emraan07** [comment] 2022-06-21 09:19
> for i in range(10):
>     pg.press("tab")
> pg.press("enter")

This worked like a charm, thanks

**Comment by Mekatroniktr** [comment] 2022-09-06 16:08
wait_time must be greater than 7.
Increasing wait time for ex. 15 minutes will solve the problem.
It worked for me.
You dont have to change 7. Instead increase wait time...

**Comment by gargahcerk** [comment] 2022-09-21 19:35
I had the same issue and copyq was the cause for me. I suggest 
1. make sure copyq is installed
2. if it still doesnt work try it with xclip:
in core.py - copy_image() instead of `os.system(f"copyq copy image/png - < {path}")` write `os.system(f"xclip -selection clipboard -t image/png -i {path}")`

**Comment by androshalikashvili** [comment] 2023-03-26 12:01
i have 2 monitors , and i resolve this problem with comment 30 line in venv\lib\site-packages\pywhatkit\whats.py 

![123](https://user-images.githubusercontent.com/20586611/227774052-b93fd30f-5cb8-4fa7-a336-e152b91e4c1c.PNG)

**Comment by rollip** [comment] 2023-04-21 15:06
> i have 2 monitors , and i resolve this problem with comment 30 line in venv\lib\site-packages\pywhatkit\whats.py
> 
> ![123](https://user-images.githubusercontent.com/20586611/227774052-b93fd30f-5cb8-4fa7-a336-e152b91e4c1c.PNG)

Helped me out also! 1 monitor, can't see obvious reason for that, anyway :)
