### ISSUE TITLE
Different format when sending in group vs a single person

### ISSUE THREAD

**Issue by diegomora02** [Ankit404butfound/PyWhatKit#111] opened 2021-08-07 16:57 UTC
Hi, When I send the a message to a singular person I get the format I want, but when I send the same text to a group it sends as different messages and without accents (the text is in Spanish), how could I fix this issue? I know it's the same exact message because it is stored in a variable.
pwk.sendwhatmsg("+xxxxxxxxx", Msj, 11, 5, 30, True)
![SinglePerson](https://user-images.githubusercontent.com/31973242/128607990-e4771230-f2b4-45cd-8e6d-a01ae7e06434.jpg)
Vs 
pwk.sendwhatmsg_to_group("xxxxxxxxxxx", Msj, 10, 59, 30, True)
![Group](https://user-images.githubusercontent.com/31973242/128608012-b85701da-39ef-404a-82a7-048131b12980.jpg)
And the variable looks like this:
Msj = """Buenos días!
Les paso el link de la reunión: https://xxxxxxxxxxxx
Los veo en una hora :)
"""

**Comment by aaryanrr** [comment] 2021-08-08 16:27
Hey @diegomora02 , this is actually the way WhatsApp Group Messages Work. All the messages are typed in the field rather than passing it on to a parameter in URL as compared to sending individual messages. We'll try to find a fix for this. Thanks for reporting.

**Comment by codewithpom** [comment] 2021-09-06 03:05
@aaryanrr I know how to fix the accent actually the problem is that pyautogui on line breaks presses enter and that is why every line is sent separately and in single person the message is parsed just from the URL.I know how to fix this please ping me here or in Mods category in the discord server.

**Comment by codewithpom** [comment] 2021-09-06 13:53
@diegomora02 Do not worry we have fixed the format error of new lines and we are working on accent and I have approximately solved it

**Closed** 2021-09-09 14:30 UTC
Labels: bug, enhancement
