### ISSUE TITLE
Not able to send message using sendwhatmsg function

### ISSUE THREAD

**Issue by buharshe** [Ankit404butfound/PyWhatKit#20] opened 2020-10-30 05:48 UTC
**Describe the bug**
Not able to send message using sendwhatmsg function. 
It is just copying the message in the text field of recipient but it is not sent automatically. 

**Expected behavior**
it should send the message but message is just copied to the text field and not sent. 

**Desktop (please complete the following information):**
 - OS: [Win 10]
 - Browser [ chrome]

**Comment by Ankit404butfound** [comment] 2020-11-01 05:18
This might be due to slow internet connection.

**Comment by AhmedAbo6** [comment] 2020-11-18 01:44
I have the same issue on Edge browser!

**Comment by Ankit404butfound** [comment] 2020-11-19 03:16
> I have the same issue on Edge browser!

I will have to check, what's wrong. Meanwhile try to set wait_time=30.

**Comment by bglxbully** [comment] 2020-11-19 16:25
Hey pal, I was having same issue...  I took out the "pg.click(width/2,height/2)" line under the sendwhatmsg function and it seems to work.

I was finding that on Chrome (Version 87.0.4280.66), it would populate the message, then click out of the text box and then the enter press wouldn't recognize. 

Module is great, thanks a lot.

**Comment by pycharm17** [comment] 2020-12-17 13:28
Not able to send message using sendwhatmsg function.
It is just copying the message in the text field of recipient but it is not sent automatically. 

i am using chrome and on mac.

i have tired by giving wait_time=60 also still not able to figure out the issue.

Need your help in resolving this?

**Comment by Ankit404butfound** [comment] 2020-12-17 15:18
> Not able to send message using sendwhatmsg function.
> It is just copying the message in the text field of recipient but it is not sent automatically.
> 
> i am using chrome Version 87.0.4280.88 and on mac.
> 
> i have tired by giving wait_time=60 also still not able to figure out the issue.
> 
> Need your help in resolving this?

First update the library then call the function again. Meanwhile don't move the mouse and let the program do whatever it's doing. Let me know if it worked.

**Comment by bglxbully** [comment] 2020-12-17 18:24
Hi, on line 145 of mainfunctions.py I commented out **pg.click(width/2,height/2)** and that resolved my issue with the message not sending automatically.

I found that this mouse click, took my cursor outside of the text box and the **pg.press('enter')** command would not execute.

**Comment by pycharm17** [comment] 2020-12-18 08:43
> > Not able to send message using sendwhatmsg function.
> > It is just copying the message in the text field of recipient but it is not sent automatically.
> > i am using chrome Version 87.0.4280.88 and on mac.
> > i have tired by giving wait_time=60 also still not able to figure out the issue.
> > Need your help in resolving this?
> 
> First update the library then call the function again. Meanwhile don't move the mouse and let the program do whatever it's doing. Let me know if it worked.

I have updated lib and tried it again without moving cursor ,still same issue.

**Comment by Ankit404butfound** [comment] 2020-12-18 11:54
Did this solution work https://github.com/Ankit404butfound/PyWhatKit/issues/20#issuecomment-730487143?

**Comment by rraymond1970** [comment] 2020-12-22 00:48
> Hi, on line 145 of mainfunctions.py I commented out **pg.click(width/2,height/2)** and that resolved my issue with the message not sending automatically.
> 
> I found that this mouse click, took my cursor outside of the text box and the **pg.press('enter')** command would not execute.

I confirmed that this fixes the problem.  Thanks!

**Comment by Ankit404butfound** [comment] 2020-12-22 01:44
> > Hi, on line 145 of mainfunctions.py I commented out **pg.click(width/2,height/2)** and that resolved my issue with the message not sending automatically.
> > I found that this mouse click, took my cursor outside of the text box and the **pg.press('enter')** command would not execute.
> 
> I confirmed that this fixes the problem. Thanks!

I will release a new update with this as an option to enable and disable with by default disabled. 
Credits: @bglxbully

**Comment by Dileep2896** [comment] 2020-12-22 11:03
I tried the #20 (Comment), And it doesn't seems to work for me
OS : Mac
Browser : Chrome

**Comment by Ankit404butfound** [comment] 2020-12-23 04:11
> I tried the #20 (Comment), And it doesn't seems to work for me
> OS : Mac
> Browser : Chrome

Is it sending without it?

**Comment by Dileep2896** [comment] 2020-12-23 07:46
Nope, at first I tried to run it without any changes in the mainfunction.py didn't got any result, and even after removing the pg.click(width/2,height/2). It doesn't seem to work. I have tried this on mac, I don't know about window users.

**Comment by Shabab-coder** [comment] 2020-12-24 20:23
Hello,
Even if I comment out pg.click(width/2,height/2) it still doesn't resolve the issue if I click the mouse anywhere right after the code starts to run, the pg.press('enter') line doesn't get executed.

**Comment by Ankit404butfound** [comment] 2020-12-25 02:56
> Nope, at first I tried to run it without any changes in the mainfunction.py didn't got any result, and even after removing the pg.click(width/2,height/2). It doesn't seem to work. I have tried this on mac, I don't know about window users.

On windows it is working for me.

**Comment by Ankit404butfound** [comment] 2020-12-25 02:56
> Hello,
> Even if I comment out pg.click(width/2,height/2) it still doesn't resolve the issue if I click the mouse anywhere right after the code starts to run, the pg.press('enter') line doesn't get executed.

You need to keep it undisturbed.

**Comment by petragom** [comment] 2021-01-10 14:00
OS: [MacOS Big Sur]
Browser [Chrome]
IDE [PyCharm]

It didn't work at first, but both removing the line mentioned in #20 or comment it out fixed my problem. And also after I click my mouse after executing.

**Comment by Ankit404butfound** [comment] 2021-01-15 11:20
A solution for this problem.
```
import pyautogui as pg
import pywhatkit as kit
kit.sendwhatmsg(...)
pg.press("enter")
```
Please let me know if it is working.

**Comment by abdiels** [comment] 2021-01-20 17:28
This is not working for me.
OS: [MacOS Mojave]
Browser [Vivaldi]
IDE [IntelliJ]
It was not working, I added the pg.press("enter") and that did not do the trick.

**Comment by Ankit404butfound** [comment] 2021-01-21 04:08
> This is not working for me.
> OS: [MacOS Mojave]
> Browser [Vivaldi]
> IDE [IntelliJ]
> It was not working, I added the pg.press("enter") and that did not do the trick.

Ok, let me see what can be done.

**Comment by ameya-r** [comment] 2021-01-25 14:01
By commenting line **pg.click(width/2,height/2)**  (line 147 : pywhatkit 3.9), it worked for me.
Chrome version : Version 89.0.4385.0
Python version : 3.9.1

**Comment by Ankit404butfound** [comment] 2021-01-25 15:32
Hey everyone, this is for those whom the above solution didn't work,
Add this segment in the mainfunctions.py...
```
prev_color = pg.pixel(int(width/2),int(height/2))
    while prev_color == pg.pixel(int(width/2),int(height/2)):
        pass
```
So your final code should look like this
![image](https://user-images.githubusercontent.com/54436840/105727004-a2e6f700-5f50-11eb-973d-2b0052fbe126.png)
If this worked, I will update the package.

**Comment by Dileep2896** [comment] 2021-01-25 16:31
This doesn't seems to work for me
Chrome version : Version 87.0.4280.141
Python version : 3.9.1
OS : Mac Big Sur

**Comment by Ankit404butfound** [comment] 2021-01-26 03:15
Sorry I forgot, please add desired delay before and after the code.
```
time.sleep(5)
prev_color = pg.pixel(int(width/2),int(height/2))
    while prev_color == pg.pixel(int(width/2),int(height/2)):
        pass
time.sleep(3)
```

**Comment by atulsingh1204** [comment] 2021-02-03 09:39
> **Describe the bug**
> Not able to send message using sendwhatmsg function.
> It is just copying the message in the text field of recipient but it is not sent automatically.
> 
> **Expected behavior**
> it should send the message but message is just copied to the text field and not sent.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [Win 10]
> * Browser [ chrome]

It happens because might be your network is slow. In my case, my tab was taking too much time to load which's why couldn't send it within the time period. And once the time period is over then it will not send.

**Comment by Dileep2896** [comment] 2021-02-04 06:07
> > **Describe the bug**
> > Not able to send message using sendwhatmsg function.
> > It is just copying the message in the text field of recipient but it is not sent automatically.
> > **Expected behavior**
> > it should send the message but message is just copied to the text field and not sent.
> > **Desktop (please complete the following information):**
> > 
> > * OS: [Win 10]
> > * Browser [ chrome]
> 
> It happens because might be your network is slow. In my case, my tab was taking too much time to load which's why couldn't send it within the time period. And once the time period is over then it will not send.

So maybe we need to increase the send time from '20' sec to '60' sec I guess it will work..

**Comment by obinakiller** [comment] 2021-02-19 11:49
Has there ever been a definitive solution? I have the same problem and none of the solutions proposed in the previous messages worked for me.
I'm using: Windows and Chrome 88.0.4324.182 (64-bit)

**Comment by 01ritvik** [comment] 2021-03-23 12:56
my program is working fine but whenever i try to send message to any unsaved number it just copies the text but does not send it automatically

**Comment by ThomasHaarlem** [comment] 2021-04-11 19:46
OS: win10
Browser: Firefox
IDE: Anaconda Spyder

I have the same problem.
I think the problem is that it doenst keep the web.whatsapp window as the active window. 
When I see the text copied in the browser (firefox), I see after the 20 seconds delay, a "return" in my Python IDE

**Comment by ThomasHaarlem** [comment] 2021-04-11 19:51
> Hi, on line 145 of mainfunctions.py I commented out **pg.click(width/2,height/2)** and that resolved my issue with the message not sending automatically.
> 
> I found that this mouse click, took my cursor outside of the text box and the **pg.press('enter')** command would not execute.

actually the pg.press("enter") command did execute except in a different window (in windows). 
For example, a white line appeared in my Python  IDE: anaconda - Spyder.

**Comment by oliveiradeflavio** [comment] 2021-05-02 02:10
> Hi, on line 145 of mainfunctions.py I commented out **pg.click(width/2,height/2)** and that resolved my issue with the message not sending automatically.
> 
> I found that this mouse click, took my cursor outside of the text box and the **pg.press('enter')** command would not execute.


I tested on macOS, using Chrome version 90 commenting ** pg.click (width / 2, height / 2) ** and even so it didn't work. Someone else managed to run on macOS Chrome?

**Comment by ThomasHaarlem** [comment] 2021-05-02 10:19
> > Hi, on line 145 of mainfunctions.py I commented out **pg.click(width/2,height/2)** and that resolved my issue with the message not sending automatically.
> > I found that this mouse click, took my cursor outside of the text box and the **pg.press('enter')** command would not execute.
> 
> I tested on macOS, using Chrome version 90 commenting ** pg.click (width / 2, height / 2) ** and even so it didn't work. Someone else managed to run on macOS Chrome?

at which point exactly does it not work? As you can see in my previous reply, the whole script  does run. Only the 'enter' executes in a different (active) window instead of in the webbrowser for web.whatsapp.

**Comment by oliveiradeflavio** [comment] 2021-05-02 13:15
> at which point exactly does it not work? As you can see in my previous reply, the whole script does run. Only the 'enter' executes in a different (active) window instead of in the webbrowser for web.whatsapp.

yes yes, my script is executed, it opens the site web.whatsapp and with the message ready to be sent, but it is interrupted there. Sending the message to the recipient is not performed.

**Comment by oliveiradeflavio** [comment] 2021-05-02 17:26
> prev_color = pg.pixel(int(width/2),int(height/2))
>     while prev_color == pg.pixel(int(width/2),int(height/2)):
>         pass

Guys, I did a test on a VM with **Windows 10 and Chrome version 90**. Using the **white theme web.whatsApp** and with this change in Main.py the message sending **worked**. However, using _macOS system with chrome 90_, the script reaches the message sending screen to the recipient, but does **not send, as if the "enter" was missing**.

**Comment by Sachit71** [comment] 2021-05-02 17:29
As far as I know, the message is sent 20 seconds after WhatsApp web is opened.

**Comment by jaovssilva** [comment] 2021-05-12 21:37
Any solution? for 'enter' in different window

**Comment by Sachit71** [comment] 2021-05-14 06:31
Hey, there!
Can you please elaborate on your issue?
Thanks,
Sachit

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Sachit71** [comment] 2021-05-14 06:33
> Any solution? for 'enter' in a different window

Also as stated earlier, as soon as the window opens, and sends the message 20 seconds later.

**Comment by 201903022** [comment] 2021-05-14 06:56
> mainfunctions.py
how can i open this?

**Comment by aaryanrr** [comment] 2021-05-14 07:37
You need to find the location where the library is installed, if it is installed in a virtual environment then it will be under `venv/site-packages` otherwise you need to find the location of python installation on your PC. There under `lib/site-packages/` you should see pywhatkit's folder.

**Comment by 201903022** [comment] 2021-05-14 07:41
Thanks, but IDK but the problema was when pywhatkit opens WhatsApp in the
second monitor's laptop

**Comment by aaryanrr** [comment] 2021-05-14 07:44
Currently the library doesn't support multiple monitors, the browser needs to be on the same monitor where the program is being run.

**Comment by 201903022** [comment] 2021-05-14 14:28
Ok, thanks. For the support

**Comment by ThomasHaarlem** [comment] 2021-05-16 09:42
> Currently the library doesn't support multiple monitors, the browser needs to be on the same monitor where the program is being run.

I think that is it! I do have a 2-monitor setup and indeed the web.whatsapp window opens on the left monitor while my python-script is running on the right monitor. And after that 20 second delay I see a white line appearing on the right monitor, like the <enter> command is executed there.

**Comment by danielGoosen** [comment] 2021-06-03 20:04
I had the same issue with whatsapp opening but the cursor was gone. 

So I investigate by minimizing all other windows with just my script opened in Jupyter. The code executed perfectly and the cursor was visible in the text box. 

I tried it again but this time had a word doc open behind the jupyter chrome tab. Whatsapp opened in a new tab but there was no cursor. 

So for some reason the cursor jumps to a different layer of opened windows. I don't have the solution sorry

**Comment by alphonse55** [comment] 2021-07-04 19:02
I had so much trouble with this but I finally found the solution. I thought the problem may actually come from "pg.press('enter')" so I tried to run it on its own and it didn't work indeed. Turns out you need to allow your terminale (or in my case VS Code) to modify Accessibility settings on macOS Big Sur.

**Comment by claytonmaciel** [comment] 2021-07-05 14:45
My environment:
[OS: macOs Big Sur 11.4]
[Browser:O Google Chrome 91.0.4472.114]
[IDE: PyCharm CE 2021.1.3]

First, I modified the Accessibility settings on macOS Big Sur to allow the PyCharm CE.

After, I added "pg.press(“enter")" after sendwhatmsg method. Without this command, the message was not being sent.

It is working for me. Thanks all.

**Comment by claytonmaciel** [comment] 2021-07-05 17:06
My environment: 
[OS: macOs Big Sur 11.4] 
[Browser:O Google Chrome 91.0.4472.114]
 [IDE: PyCharm CE 2021.1.3]
First, I modified the Accessibility settings on macOS Big Sur to allow the PyCharm CE.
After, I do the code below.

kt.sendwhatmsg_instantly("+######", "Hello!")
pg.press("tab")
pg.press("tab")
pg.press("tab")
pg.press("tab")
pg.press("tab")
pg.press("enter")

It just worked that way for me. Thanks all.

**Comment by nozzzyyy** [comment] 2021-07-15 19:10
The solution in macOS Big Sur is allow the Accessibility of your terminal, VS Code or w/e u are running the script with. Modify Accessibility settings on macOS Big Sur.

For Linux (Ubuntu) and Windows its working without doing anything (from IDE or terminal)

**Comment by aaryanrr** [comment] 2021-08-30 18:58
Hope that everyone is able to use the function without any issues. Closing this issue for now!

**Closed by aaryanrr** 2021-08-30 18:58 UTC
Labels: bug, User Question

**Comment by pugazhr** [comment] 2021-09-17 12:08
> Hey pal, I was having same issue... I took out the "pg.click(width/2,height/2)" line under the sendwhatmsg function and it seems to work.
> 
> I was finding that on Chrome (Version 87.0.4280.66), it would populate the message, then click out of the text box and then the enter press wouldn't recognize.
> 
> Module is great, thanks a lot.

how to modify similar to this, i am also facing same issue

**Comment by pugazhr** [comment] 2021-09-17 14:10
> pg.press("tab")
> pg.press("tab")
> pg.press("tab")
> pg.press("tab")
> pg.press("tab")
> pg.press("enter")

this worked for me as well, IDE and browser should be in same window

**Comment by isew25** [comment] 2021-09-18 14:36
win 10, jupyter notebook, chrome

.sendwhatmsg_instantly(............)
pg.press("tab")
pg.press("tab")
pg.press("tab")
pg.press("tab")
pg.press("tab")
pg.press("tab")
pg.press("tab")
pg.press("tab")
pg.press("enter")

worked for me

**Comment by ajayyadav1998** [comment] 2021-09-24 05:18
> A solution for this problem.
> 
> ```
> import pyautogui as pg
> import pywhatkit as kit
> kit.sendwhatmsg(...)
> pg.press("enter")
> ```
> 
> Please let me know if it is working.

This is also not working

**Comment by aaryanrr** [comment] 2021-09-24 06:43
@ajayyadav1998, This bug has been fixed in version 5.2. It will be released before tomorrow.

**Comment by KiaraEvers** [comment] 2021-09-28 09:34
> @ajayyadav1998, This bug has been fixed in version 5.2. It will be released before tomorrow.

I did not see a new release, do you know when the new release will be? :)

**Comment by aaryanrr** [comment] 2021-09-28 14:45
@KiaraEvers Sorry for the delay. There are a few bugs in the new version and we are working on a fix for them. It will be released soon.

**Comment by Biancaa-R** [comment] 2021-10-01 17:49
> A solution for this problem.
> 
> ```
> import pyautogui as pg
> import pywhatkit as kit
> kit.sendwhatmsg(...)
> pg.press("enter")
> ```
> 
> Please let me know if it is working.

Yes it worked like magic

**Comment by KiaraEvers** [comment] 2021-10-06 14:25
> @KiaraEvers Sorry for the delay. There are a few bugs in the new version and we are working on a fix for them. It will be released soon.

Thank you for your comment, i actually have some deeper questions about the code itself aswell, is there anyway we can communicate about this? :)

**Comment by KiaraEvers** [comment] 2021-10-06 15:00
> > > @KiaraEvers Sorry for the delay. There are a few bugs in the new version and we are working on a fix for them. It will be released soon.
> > 
> > 
> > Thank you for your comment, i actually have some deeper questions about the code itself aswell, is there anyway we can communicate about this? :)
> 
> Yep sure. You can join our discord server [here](https://discord.gg/62Yf5mushu).

Thank you! I also have sent you a message on twitter :)

**Comment by kranthinb** [comment] 2021-10-30 15:25
kit.sendwhatmsg("+xxxxx", "hello", hours,minutes+1,wait_time=5)
time.sleep(5)
width, height = pg.size()
pg.click(width / 2, height / 2)
pg.press('enter')


#the error is that latest whatsapp web is loading few seconds late and the cursor is clicked at that time..so everyone facing the issue.

**Comment by aaryanrr** [comment] 2021-10-30 18:22
> is update relased i am facing same issue of not sending automaticlly

It will be released shortly. Thanks for bearing with us!

**Comment by Abdulla-hamideh** [comment] 2021-11-06 10:20
import pywhatkit as py
import random
import pyautogui as pg
import time
import keyboard as k
py.sendwhatmsg(phone_no="+962xxxxx",message= "hello" ,time_hour=13, time_min=18)
pg.click(1050, 950)
time.sleep(2)
k.press_and_release('enter')

this should work

**Comment by Victoro87** [comment] 2021-11-08 17:48
> import pywhatkit as py import random import pyautogui as pg import time import keyboard as k py.sendwhatmsg(phone_no="+962xxxxx",message= "hello" ,time_hour=13, time_min=18) pg.click(1050, 950) time.sleep(2) k.press_and_release('enter')
> 
> this should work

How would you close the window with this? im using

pwt.sendwhatmsg_instantlyphone_no="+962xxxxx",message= "hello", wait_time=40, tab_close=True, close_time= 10)

**Comment by refranco** [comment] 2021-11-11 17:35
> > Not able to send message using sendwhatmsg function.
> > It is just copying the message in the text field of recipient but it is not sent automatically.
> > i am using chrome Version 87.0.4280.88 and on mac.
> > i have tired by giving wait_time=60 also still not able to figure out the issue.
> > Need your help in resolving this?
> 
> First update the library then call the function again. Meanwhile don't move the mouse and let the program do whatever it's doing. Let me know if it worked.

What works for me in different computers, all working at the same time sending messages. 
- python 3.8 (One PC windows Anaconda, One PC windows with pip installation, and the last one Linux within a virtual environment: ds).

I went to the main function of the library at: _/home/$USER/.virtualenvs/ds/lib/python3.8/site-packages/pywhatkit/main.py_

main.py in **sendwhatmsg_instantly**

`    web.open('https://web.whatsapp.com/send?phone=' +
             phone_no + '&text=' + parsed_message)
    time.sleep(2)
    width, height = pg.size()
    pg.click(width / 2, height / 2)
    time.sleep(wait_time - 2)`
after this last line, I add a `pg.click(width / 2, height / 2)` before the line `pg.press('enter')`

That would make my pc to place the screen in WhatsApp before pressing enter to send the message, I could event send a message with just 8 seconds of waiting time.

**Comment by shadowfax-ng** [comment] 2021-11-20 20:08
@Ankit404butfound Any update on this issue. The issue still persists!
![image](https://user-images.githubusercontent.com/66220509/142739621-ff55f893-8434-475e-b2c2-ad4056a551c7.png)

**Comment by shadowfax-ng** [comment] 2021-11-20 20:11
@Ankit404butfound Any update on this issue. The issue still persists! Text just stays in the box and doesn't get sent. I uninstalled and reinstalled pywhatkit just to be sure I was using the latest update.

![image](https://user-images.githubusercontent.com/66220509/142739684-9c0a0fef-1c71-409e-a7a0-75ab99c8f6b0.png)

**Comment by fahad-programmer** [comment] 2022-01-03 08:55
The Error can be solved just by closing all the tabs of web whatsapp before starting the program and every problem will be solved

**Comment by rkalyankumar** [comment] 2022-01-04 04:28
Sequence of pg.press('tab') and pg.press('enter') works well. The issue still persists as of 4th January 2022 and not resolved. I would be wondering why this issue is closed without any resolution. 
PS: I tested the script in two laptops (one running windows 10 & Chrome and another one running Ubuntu 20.04 & Chrome).
This issue is in "pywhatkit" and not elsewhere. It isn't clicking the "Send" button in the whatsapp.

**Comment by braulio-arteaga** [comment] 2022-01-05 19:07
I used this solution:

import pywhatkit as w
import time
import pyautogui
import keyboard as k
w.sendwhatmsg("your number", 'hi', 8, 38)
pyautogui.click(1050, 950)
time.sleep(2)
k.press_and_release('enter')

¡worked for me!

**Comment by pankaj-rathi** [comment] 2022-01-14 05:16
The reason why the send doesn't work is on Mac 

When the click function and press function is invoked, I see the Python Rocket ship icon in the dock keeps popping and that is the reason it looses the web browser window context and the press enter function doesn't work as the context is moved out of the whatsapp window

**Comment by theCJMan** [comment] 2022-01-18 06:14
This is still an issue for me.
Chrome Version 97.0.4692.71 (Official Build) (64-bit)
Win 10 V 21H1
Line speed 20m/s

PyWhatKit 5.3
Python 3.9

I had to include flask else the code would not work, I tried to work with and without the pg.click() -> pg.click seems to make it worse as the system then clicks on weird places and NO, I did not move my mouse
I also tried to even increase to 60 sec delay instead of 15, then it seems the code does not stop running...
```
import pywhatkit as wu
import flask
import pyautogui as pg

wu.sendwhatmsg_instantly("+27790995412", "Test this now", 15)
pg.click()
```

**Comment by smah1980** [comment] 2022-01-28 20:05
just explaining the solution given by @refranco is
if you are using pywhatkit version 5.3
then edit whats.py
goto method sendwhatmsg_instantly
copy pg.click(core.WIDTH / 2, core.HEIGHT / 2) and paste it before  pg.press("enter")

then code should be look like
`    time.sleep(4) 
    pg.click(core.WIDTH / 2, core.HEIGHT / 2)
    time.sleep(wait_time - 4)
    pg.click(core.WIDTH / 2, core.HEIGHT / 2)
    pg.press("enter")`

**Comment by smah1980** [comment] 2022-01-28 20:16
while for sendwhatmsg
goto core.py 
in send_message method and add click(WIDTH / 2, HEIGHT / 2) after time.sleep(wait_time - 7)

**Comment by masoodahamedgit** [comment] 2022-02-21 21:34
> Message is being typed but not sent #149

Just explaining the solution given by @refranco is
if you are using pywhatkit version 5.3
then edit whats.py
goto method sendwhatmsg_instantly
copy pg.click(core.WIDTH / 2, core.HEIGHT / 2) and paste it before pg.press("enter")

then code should be look like
time.sleep(4) pg.click(core.WIDTH / 2, core.HEIGHT / 2) time.sleep(wait_time - 4) pg.click(core.WIDTH / 2, core.HEIGHT / 2) pg.press("enter")

@smah1980 i tried this in Mac - but it doesn't work, means the message doesn't get sent.

**Comment by katiakdev** [comment] 2022-03-24 19:47
> **Describe the bug** Not able to send message using sendwhatmsg function. It is just copying the message in the text field of recipient but it is not sent automatically.
> 
> **Expected behavior** it should send the message but message is just copied to the text field and not sent.
> 
> **Desktop (please complete the following information):**
> 
>     * OS: [Win 10]
> 
>     * Browser [ chrome]

Not working for me also: Ubuntu 20.04, brownser: Firefox.

**Comment by kxnyshk** [comment] 2022-04-28 14:03
> I used this solution:
> 
> import pywhatkit as w import time import pyautogui import keyboard as k w.sendwhatmsg("your number", 'hi', 8, 38) pyautogui.click(1050, 950) time.sleep(2) k.press_and_release('enter')
> 
> ¡worked for me!
> 
> Source: https://stackoverflow.com/questions/65212520/pywhatskit-on-python-not-sending-message

@braulio-arteaga This seems to work for now, only if you select the chrome window/tab that has been opened by python script since it opens in the background for me (I had to switch from my IDE to Chrome), then only the mouse cursor clicks on the desired (x,y) co-ordinates and hits "enter" as specified in the script.

I wonder if there's any way to make the python opened chrome window automatically come to foreground and be the currect active window?

**Comment by Naman23-coder** [comment] 2022-04-28 16:10
@kxnyshk try solutions in #149  too

**Comment by adlardbradford** [comment] 2022-05-11 01:27
This worked each time for me:
1. python -m pip install keyboard
2. Edit core.py
3. from keyboard import press
4. Save and close core.py

**Comment by Nilesh-Kadivar-Einfochips** [comment] 2022-05-17 11:59
> I used this solution:
> 
> import pywhatkit as w import time import pyautogui import keyboard as k w.sendwhatmsg("your number", 'hi', 8, 38) pyautogui.click(1050, 950) time.sleep(2) k.press_and_release('enter')
> 
> ¡worked for me!
> 
> Source: https://stackoverflow.com/questions/65212520/pywhatskit-on-python-not-sending-message

I tried all the above solution posted in this link but didn't worked. Finally this given fix worked for me.

**Comment by teguhsms05** [comment] 2022-07-13 08:01
> A solution for this problem.
> 
> ```
> import pyautogui as pg
> import pywhatkit as kit
> kit.sendwhatmsg(...)
> pg.press("enter")
> ```
> 
> Please let me know if it is working.

I have tried ur solution, but still not working for me

*OS: MacOS BigSur
*Browser: Chrome

**Comment by Jafar369** [comment] 2022-08-17 16:46
> Hi, on line 145 of mainfunctions.py I commented out **pg.click(width/2,height/2)** and that resolved my issue with the message not sending automatically.
> 
> I found that this mouse click, took my cursor outside of the text box and the **pg.press('enter')** command would not execute.



> Hi, on line 145 of mainfunctions.py I commented out **pg.click(width/2,height/2)** and that resolved my issue with the message not sending automatically.
> 
> I found that this mouse click, took my cursor outside of the text box and the **pg.press('enter')** command would not execute.

how to find "mainfunction.py"

**Comment by Jafar369** [comment] 2022-08-18 08:02
> > Hi, on line 145 of mainfunctions.py I commented out **pg.click(width/2,height/2)** and that resolved my issue with the message not sending automatically.
> > I found that this mouse click, took my cursor outside of the text box and the **pg.press('enter')** command would not execute.
> 
> I confirmed that this fixes the problem. Thanks!

How to find the "mainfunctions.py"

**Comment by codebuddy123** [comment] 2023-06-15 08:17
> Hi, on line 145 of mainfunctions.py I commented out **pg.click(width/2,height/2)** and that resolved my issue with the message not sending automatically.
> 
> I found that this mouse click, took my cursor outside of the text box and the **pg.press('enter')** command would not execute.

Hey, where actually this file mainfunctions.py is?

**Comment by CalebMtuwetaM** [comment] 2023-10-29 21:05
> > Hi, on line 145 of mainfunctions.py I commented out **pg.click(width/2,height/2)** and that resolved my issue with the message not sending automatically.
> > I found that this mouse click, took my cursor outside of the text box and the **pg.press('enter')** command would not execute.

The function is in whats.py but then line 145 is different but it is still not working

**Comment by martinolmos** [comment] 2023-12-19 14:04
> The reason why the send doesn't work is on Mac
> 
> When the click function and press function is invoked, I see the Python Rocket ship icon in the dock keeps popping and that is the reason it looses the web browser window context and the press enter function doesn't work as the context is moved out of the whatsapp window

Yes, this was exactly what was happening to me on Macos Ventura 13.5.1
I fixed it by changing Accessibility settings to allow VSCode to control my computer.

**Comment by nashrepos** [comment] 2024-01-05 10:50
> > The reason why the send doesn't work is on Mac
> > When the click function and press function is invoked, I see the Python Rocket ship icon in the dock keeps popping and that is the reason it looses the web browser window context and the press enter function doesn't work as the context is moved out of the whatsapp window
> 
> Yes, this was exactly what was happening to me on Macos Ventura 13.5.1 I fixed it by changing Accessibility settings to allow VSCode to control my computer.

Thanks. My issue got resolved after I have give permission to VSCode in the accessibility of settings.

**Comment by botpromax1** [comment] 2024-02-24 08:14
import pywhatkit as w
import time
import pyautogui
import keyboard as k
w.sendwhatmsg("your number", 'hi', 8, 38)
pyautogui.click(1050, 950)
time.sleep(2)
k.press_and_release('enter')

This works for me !!! Finally after trying 1000 times .

**Comment by bekirbostanci** [comment] 2024-05-23 20:58
![Screen Shot 2024-05-23 at 23 54 21](https://github.com/Ankit404butfound/PyWhatKit/assets/26343575/25e367b3-ad4d-4068-8588-53318389e0cc)
I had same problem in my mac os.I tried with different browsers, safari, chrome and opera and all of them had same problem. Message written but it didnt send message. Just when I checked I saw, vscode doesnt allow to accessibility. When I changed it, **it worked.**

OS: mac os 
Interpreter: vscode

**Comment by murtuzamvista** [comment] 2025-04-28 10:27
MacOS Sequoia: 15.4.1
Chrome Version: 135.0.7049.115 (Official Build) (arm64)
iTerm2: Build 3.5.11
Python: 3.13.1
pywhatkit: 5.4

Thanks for all the comments with solutions! Finally the below works from the iterm2 terminal after doing the following 2 additional steps: 

1. Allowing `Accessibility` to `iterm2` from `Privacy & Security` from `System Settings` on `Macbook`.
2. Disconnect any monitor(s) if connected.

```
import pywhatkit as kit
import time

contacts = ["+91xxxxxxxxxx", "+91xxxxxxxxxx"]
message = "Hello from Python, Macbook!"

for contact in contacts:
    kit.sendwhatmsg_instantly(contact, message, wait_time=10, tab_close=True)
    time.sleep(5)
```
